spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/datviet_dev_db
        username: postgres
        password: kolothefourth4$
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update

        

